# Generated by Django 2.2.6 on 2019-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('review', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('duration', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('rate', models.FloatField()),
                ('cast', models.TextField()),
                ('trailer', models.TextField()),
                ('director', models.TextField()),
                ('genre', models.ManyToManyField(to='catalog.Genre')),
            ],
        ),
    ]
