# Generated by Django 2.2.6 on 2019-10-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img_source',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_source',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='parsing_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
