# Generated by Django 2.2.6 on 2019-10-15 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191015_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='parsing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
